@startuml jaloguin

class Ninie{
    elementosPuestos
    actitud
    caramelos
    estadoDeSalud = sano

    caramelos()
    elementosPuestos()
    sustoDeElementos()
    capacidadDeSusto()
    asustar(unAdulto)
    recibirCaramelos(cantidad)
    tieneMasDeNCaramelos(N)
    alimentarse(unosCaramelos)
    digerirCaramelos(unosCaramelos)
    disminuirActitud(cantidad)
}

abstract class Adulto{
    niniosQueIntentaronAsustarlo

    asustadoresConMuchosCaramelos()
    tolerancia()
    serAsustado(unNinie)
    darCaramelos()
}

class AdultoComun {
}

class Anciano {

}

class AdultoNecio{
    serAsustado(unNinie)
}

interface elementosPuestos{
    cuantoAsusta()
}

object maquillaje{

    nivelDeSusto = 3

    --
    cambiarNivelDeSusto(cantidad)
}

object traje{
    personaje
}

abstract class Personaje{

    nivelDeSusto()
    nivelTipoDePersonaje
}

class PersonajeTierno{
}

class PersonajeTerrorifico{
}

class Legion{
    miembros

    capacidadDeSusto()
    caramelos()
    lider()
    asustar(unAdulto)
}

class Barrio{

    niniesDelBarrio

    ordenarPorCaramelos(unosNinies)
    losTresConMasCaramelosDelRrioba()
    niniesConMuchosCaramelos(unosNinies)
    elementosDeNinies(unosNinies)
    elementosDeNiniosConMuchosCaramelos()
}

interface EstadoDeSalud{

    repercutirse()
    afectarCuerpo(unHumano)
    puedeSeguirComiendo

}

abstract class EstadoDeSaludActivo{

    estadoDeSaludSiguiente 
}

object sano{
}

object empachado{
}

object enCama{
}

PersonajeTierno -u-|> Personaje
PersonajeTerrorifico -u-|> Personaje

AdultoComun -u-|> Adulto
Anciano -u-|> Adulto

sano -u-|> EstadoDeSalud
empachado -u-|> EstadoDeSalud

EstadoDeSaludActivo .u.|> EstadoDeSalud
enCama .u.|> EstadoDeSaludActivo


traje -r-> Personaje

Ninie -r-> "*" elementosPuestos : elementosPuestos
Ninie -r-> EstadoDeSalud
Ninie ..> Adulto
Ninie ..> AdultoNecio

Barrio -r-> "*" Ninie : niniesDelBarrio

Legion -r-> "*" Ninie : miembros
Legion ..> Adulto
Legion ..> AdultoNecio

traje .u.|> elementosPuestos
maquillaje .u.|> elementosPuestos


@enduml